<?php
/**
 * KMC Robotics Club - Installation Script
 * Run this script once to set up the application
 * 
 * Usage: Navigate to /install.php in your browser
 * DELETE THIS FILE AFTER INSTALLATION!
 */

error_reporting(E_ALL);
ini_set('display_errors', 1);

$step = $_GET['step'] ?? 1;
$errors = [];
$success = [];

// Check if already installed
$configExists = file_exists('config/config.php');
$installedFile = file_exists('.installed');

if ($installedFile && $step != 'reinstall') {
    die('<div style="font-family: sans-serif; max-width: 600px; margin: 50px auto; padding: 20px; background: #1a1a2e; color: #fff; border-radius: 10px;">
        <h2 style="color: #00f2ff;">Already Installed</h2>
        <p>The application appears to be already installed. If you need to reinstall:</p>
        <ol>
            <li>Delete the <code>.installed</code> file from the root directory</li>
            <li>Refresh this page</li>
        </ol>
        <p><a href="index.php" style="color: #00f2ff;">Go to Homepage</a></p>
    </div>');
}

// Step 2: Process installation
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['install'])) {
    $dbHost = $_POST['db_host'] ?? 'localhost';
    $dbName = $_POST['db_name'] ?? 'kmcrc_db';
    $dbUser = $_POST['db_user'] ?? 'root';
    $dbPass = $_POST['db_pass'] ?? '';
    
    // Test database connection
    try {
        $pdo = new PDO(
            "mysql:host=$dbHost",
            $dbUser,
            $dbPass,
            [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]
        );
        
        // Create database if not exists
        $pdo->exec("CREATE DATABASE IF NOT EXISTS `$dbName` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
        $pdo->exec("USE `$dbName`");
        
        // Read and execute schema
        $schemaFile = 'database/schema.sql';
        if (file_exists($schemaFile)) {
            $schema = file_get_contents($schemaFile);
            
            // Split by delimiter for stored procedures
            $statements = [];
            $currentStatement = '';
            $delimiter = ';';
            
            foreach (explode("\n", $schema) as $line) {
                if (preg_match('/^DELIMITER\s+(.+)$/i', trim($line), $matches)) {
                    $delimiter = $matches[1];
                    continue;
                }
                
                $currentStatement .= $line . "\n";
                
                if (str_ends_with(trim($line), $delimiter)) {
                    $stmt = trim(str_replace($delimiter, ';', $currentStatement));
                    if (!empty($stmt) && $stmt !== ';') {
                        $statements[] = $stmt;
                    }
                    $currentStatement = '';
                }
            }
            
            // Execute each statement
            foreach ($statements as $stmt) {
                if (!empty(trim($stmt)) && trim($stmt) !== ';') {
                    try {
                        $pdo->exec($stmt);
                    } catch (PDOException $e) {
                        // Ignore duplicate key errors for re-installation
                        if (strpos($e->getMessage(), 'Duplicate') === false && 
                            strpos($e->getMessage(), 'already exists') === false) {
                            $errors[] = "SQL Error: " . $e->getMessage();
                        }
                    }
                }
            }
            
            $success[] = "Database tables created successfully!";
        } else {
            $errors[] = "Schema file not found: $schemaFile";
        }
        
        // Create upload directories
        $uploadDirs = [
            'uploads',
            'uploads/events',
            'uploads/gallery',
            'uploads/gallery/thumbnails',
            'uploads/team',
            'uploads/avatars'
        ];
        
        foreach ($uploadDirs as $dir) {
            if (!is_dir($dir)) {
                if (mkdir($dir, 0755, true)) {
                    $success[] = "Created directory: $dir";
                } else {
                    $errors[] = "Failed to create directory: $dir";
                }
            }
            
            // Create .htaccess to prevent PHP execution in uploads
            $htaccess = "$dir/.htaccess";
            if (!file_exists($htaccess)) {
                file_put_contents($htaccess, "php_flag engine off\nOptions -Indexes");
            }
        }
        
        // Update config file with database credentials
        $configContent = "<?php
/**
 * KMC Robotics Club - Configuration
 * Generated by installer on " . date('Y-m-d H:i:s') . "
 */

// Database Configuration
define('DB_HOST', '$dbHost');
define('DB_NAME', '$dbName');
define('DB_USER', '$dbUser');
define('DB_PASS', '$dbPass');
define('DB_CHARSET', 'utf8mb4');

// Application Configuration
define('APP_NAME', 'KMC Robotics Club');
define('APP_URL', '" . (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . "://{$_SERVER['HTTP_HOST']}" . dirname($_SERVER['REQUEST_URI']) . "');
define('APP_ENV', 'production');

// Session Configuration
define('SESSION_NAME', 'kmcrc_session');
define('SESSION_LIFETIME', 7200); // 2 hours
define('SESSION_SECURE', " . (isset($_SERVER['HTTPS']) ? 'true' : 'false') . ");

// File Upload Configuration
define('UPLOAD_PATH', __DIR__ . '/../uploads/');
define('MAX_UPLOAD_SIZE', 5 * 1024 * 1024); // 5MB
define('ALLOWED_IMAGE_TYPES', ['image/jpeg', 'image/png', 'image/gif', 'image/webp']);

// Email Configuration (update these for your SMTP server)
define('SMTP_HOST', 'smtp.gmail.com');
define('SMTP_PORT', 587);
define('SMTP_USER', '');
define('SMTP_PASS', '');
define('SMTP_FROM', 'noreply@kmcrc.edu.np');
define('SMTP_FROM_NAME', 'KMC Robotics Club');

// Security
define('HASH_COST', 12);
define('TOKEN_EXPIRY', 3600); // 1 hour

// Timezone
date_default_timezone_set('Asia/Kathmandu');
";
        
        if (file_put_contents('config/config.php', $configContent)) {
            $success[] = "Configuration file updated!";
        } else {
            $errors[] = "Failed to write configuration file";
        }
        
        // Create .installed marker
        if (empty($errors)) {
            file_put_contents('.installed', date('Y-m-d H:i:s'));
            $step = 'complete';
        }
        
    } catch (PDOException $e) {
        $errors[] = "Database connection failed: " . $e->getMessage();
    }
}

// Check requirements
$requirements = [
    'PHP Version >= 7.4' => version_compare(PHP_VERSION, '7.4.0', '>='),
    'PDO Extension' => extension_loaded('pdo'),
    'PDO MySQL Driver' => extension_loaded('pdo_mysql'),
    'GD Extension' => extension_loaded('gd'),
    'JSON Extension' => extension_loaded('json'),
    'config/ writable' => is_writable('config'),
    'uploads/ writable' => is_writable('.') || is_writable('uploads')
];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Install - KMC Robotics Club</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
            theme: {
                extend: {
                    colors: {
                        'dark-navy': '#050a14',
                        'light-navy': '#0a1628',
                        'accent': '#00f2ff'
                    }
                }
            }
        }
    </script>
    <link href="https://fonts.googleapis.com/css2?family=Orbitron:wght@500;700&family=Rajdhani:wght@400;500;600&display=swap" rel="stylesheet">
</head>
<body class="bg-dark-navy text-white font-sans min-h-screen">
    <div class="max-w-2xl mx-auto px-4 py-12">
        <div class="text-center mb-8">
            <div class="w-16 h-16 bg-gradient-to-br from-cyan-400 to-purple-500 rounded-lg flex items-center justify-center mx-auto mb-4">
                <span style="font-family: 'Orbitron', sans-serif;" class="font-bold text-dark-navy text-xl">KR</span>
            </div>
            <h1 style="font-family: 'Orbitron', sans-serif;" class="text-3xl font-bold mb-2">KMC Robotics Club</h1>
            <p class="text-slate-400">Installation Wizard</p>
        </div>
        
        <?php if ($step === 'complete'): ?>
            <div class="bg-light-navy rounded-lg p-8 border border-green-500/30">
                <div class="text-center">
                    <svg class="w-16 h-16 mx-auto text-green-500 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/>
                    </svg>
                    <h2 class="text-2xl font-bold text-green-400 mb-4">Installation Complete!</h2>
                    
                    <?php if (!empty($success)): ?>
                        <div class="bg-green-500/10 rounded-lg p-4 mb-6 text-left">
                            <ul class="text-green-400 text-sm space-y-1">
                                <?php foreach ($success as $msg): ?>
                                    <li>✓ <?= htmlspecialchars($msg) ?></li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                    
                    <div class="bg-slate-800/50 rounded-lg p-4 mb-6 text-left">
                        <h3 class="font-bold mb-2">Default Admin Credentials:</h3>
                        <p class="text-slate-300">Email: <code class="text-accent">admin@kmcrc.edu.np</code></p>
                        <p class="text-slate-300">Password: <code class="text-accent">Admin@123</code></p>
                        <p class="text-yellow-400 text-sm mt-2">⚠️ Change these credentials after first login!</p>
                    </div>
                    
                    <div class="bg-red-500/10 border border-red-500/30 rounded-lg p-4 mb-6">
                        <p class="text-red-400 font-bold">⚠️ IMPORTANT: Delete install.php now!</p>
                        <p class="text-slate-400 text-sm">For security reasons, remove the installation file from your server.</p>
                    </div>
                    
                    <div class="flex gap-4 justify-center">
                        <a href="index.php" class="bg-accent text-dark-navy px-6 py-3 rounded-lg font-semibold hover:bg-accent/80 transition">
                            Go to Homepage
                        </a>
                        <a href="admin/dashboard.php" class="border border-accent text-accent px-6 py-3 rounded-lg hover:bg-accent/10 transition">
                            Admin Dashboard
                        </a>
                    </div>
                </div>
            </div>
        <?php else: ?>
            <!-- Requirements Check -->
            <div class="bg-light-navy rounded-lg p-6 border border-slate-700 mb-6">
                <h2 class="text-xl font-bold mb-4">System Requirements</h2>
                <div class="space-y-2">
                    <?php foreach ($requirements as $req => $met): ?>
                        <div class="flex items-center justify-between">
                            <span><?= $req ?></span>
                            <?php if ($met): ?>
                                <span class="text-green-400">✓ OK</span>
                            <?php else: ?>
                                <span class="text-red-400">✗ Failed</span>
                            <?php endif; ?>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
            
            <?php if (!empty($errors)): ?>
                <div class="bg-red-500/10 border border-red-500/30 rounded-lg p-4 mb-6">
                    <h3 class="font-bold text-red-400 mb-2">Errors:</h3>
                    <ul class="text-red-400 text-sm space-y-1">
                        <?php foreach ($errors as $error): ?>
                            <li><?= htmlspecialchars($error) ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            
            <?php if (in_array(false, $requirements)): ?>
                <div class="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-4 mb-6">
                    <p class="text-yellow-400">Please fix the requirements above before proceeding.</p>
                </div>
            <?php else: ?>
                <!-- Installation Form -->
                <form method="POST" class="bg-light-navy rounded-lg p-6 border border-slate-700">
                    <h2 class="text-xl font-bold mb-4">Database Configuration</h2>
                    
                    <div class="mb-4">
                        <label class="block text-slate-300 mb-2">Database Host</label>
                        <input type="text" name="db_host" value="localhost" 
                               class="w-full bg-dark-navy border border-slate-700 rounded-lg px-4 py-3 text-white focus:border-accent focus:outline-none">
                    </div>
                    
                    <div class="mb-4">
                        <label class="block text-slate-300 mb-2">Database Name</label>
                        <input type="text" name="db_name" value="kmcrc_db" 
                               class="w-full bg-dark-navy border border-slate-700 rounded-lg px-4 py-3 text-white focus:border-accent focus:outline-none">
                    </div>
                    
                    <div class="mb-4">
                        <label class="block text-slate-300 mb-2">Database Username</label>
                        <input type="text" name="db_user" value="root" 
                               class="w-full bg-dark-navy border border-slate-700 rounded-lg px-4 py-3 text-white focus:border-accent focus:outline-none">
                    </div>
                    
                    <div class="mb-6">
                        <label class="block text-slate-300 mb-2">Database Password</label>
                        <input type="password" name="db_pass" 
                               class="w-full bg-dark-navy border border-slate-700 rounded-lg px-4 py-3 text-white focus:border-accent focus:outline-none">
                    </div>
                    
                    <button type="submit" name="install" 
                            class="w-full bg-accent text-dark-navy py-3 rounded-lg font-semibold hover:bg-accent/80 transition">
                        Install Application
                    </button>
                </form>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</body>
</html>
